import data 
import random
lista=[]
random.choice=['USA','AUSTRALIA','CANADA']

print(lista)




for dic in (data.personas):
        for i in  range(len(data.personas)):
            if 0<250  :
                dic['country']='USA'


        for i in range(len(data.personas)):
                if i >250 and i<500:
                    dic['country']='UK'

        for i in range(len(data.personas)):
        
                    if i >500 and i<750:
                        dic['country']='Australia'



for dic in (data.personas):
        for i in range(len(data.personas)):
                    
                        if i >750 and i<1000:
                            dic['country']='Canada'
                            break